support customer pool key
swlib/saber pull request #127
Opened 2021-05-14 11:27 UTC by amuluowin

2021-05-14 11:30 UTC, twose requested changes

2021-05-14 11:30 UTC, twose commented on src/ClientPool.php
> +            $key = empty($key) ? "{$options['host']}:{$options['port']}" : $key;
写成 `$key ?? xxx` 就行了

2021-05-14 12:48 UTC, amuluowin commented on src/ClientPool.php
> +            $key = empty($key) ? "{$options['host']}:{$options['port']}" : $key;
我原本是用$key??方式的，后来考虑到false会转空字符串与""等意

2021-05-14 13:12 UTC, sy-records commented on src/ClientPool.php
> +    public function createEx(array $options, string $key = null, bool $temp = false)
新增参数是不是应该放在后面

2021-05-14 14:35 UTC, amuluowin commented on src/ClientPool.php
> +    public function createEx(array $options, string $key = null, bool $temp = false)
这个地方是应该放后面的，我明天改下

2021-05-17 02:45 UTC, sy-records approved these changes
改下readme，加上pool_key的说明就可以了

2021-05-17 06:13 UTC, sy-records approved these changes

2021-05-17 07:18 UTC, twose commented
@amuluowin 你看看现在这样能跑吗，没有单元测试覆盖，最好能想办法加一个

2021-05-17 10:34 UTC, amuluowin commented
> @amuluowin 你看看现在这样能跑吗，没有单元测试覆盖，最好能想办法加一个

可以跑起来，我已经在用。
我还是加单元测试上去吧

2021-05-18 01:48 UTC, twose approved these changes

2021-05-18 01:49 UTC, merged

2021-05-18 01:49 UTC, twose commented
已合并, 感谢!